#!/bin/csh

# Example usage: ./plots/curve thresh=1e-6/4.5 >& std.out &
# ... will look for atomic states in data/atomic_states/H/16-115-550/thresh=1e-6/4.5

mkdir -p plots/data/raw/$1

foreach i ( 3 4 5 6 7 )
  foreach j ( 0 1 2 3 4 5 6 7 8 9 )
    python3 -u test_H.py $i.$j $1 >& plots/data/raw/$1/$i.$j.out 
  end
end
